# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftViper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftViper
  inhibit_all_warnings!

  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'RxSwiftViperTests' do
    inherit! :search_paths
    # Pods for testing
    inhibit_all_warnings!
    pod 'Quick'
    pod 'Nimble'
  end

  target 'RxSwiftViperUITests' do
    # Pods for testing
  end

end
